### ISSUE TITLE
求RTL文件下对应每个模块的modelsim仿真测试代码！

### ISSUE THREAD

**Issue by red1508** [WangXuan95/FpOC#1]
作者您好！ 能加个联系方式吗？很紧急，需要modelsim仿真测试代码，请问您有仿真代码吗？谢谢！

**Comment by red1508** [comment]
急需仿真测试代码！ 方便的话能加个联系方式吗？我微信： lpf360726

**Comment by WangXuan95** [comment]
你好，我没有对该工程进行整体仿真，因为仿真法很难模拟出电机的行为。但是为了验证正确性，我分模块单独进行了一些仿真，一些复杂的模块我用 SystemVerilog 写了 testbench （我没有把testbench挂在github上），简单的模块我就没写 testbench ，因为能保证肯定没问题。你可以阅读每个模块的定义来自己写 testbench 进行验证（因为输入输出都不复杂，所以 testbench 写起来非常简单）。我已加你微信。

**Comment by xiao162** [comment]
作者您好！想向你请教关于fpga控制电机方面的知识，可以加个微信吗，微信号18297670446

**Comment by ZhangYH1999** [comment]
作者您好!我有个问题想问您，第一，相电流低压侧三电阻采样需要运放放大电流信号才能作为AD输入吧，但您的PCB图并没有运放放大，请问您是如何处理的？ 第二，三电阻采样您电流重构的那部分代码如何理解呢？为什么ia= ADCb + ADCc - 2*ADCa。方便的话可以加个联系方式嘛？微信号：ZYH336614215。期待您的回复！
