### ISSUE TITLE
电流采样问题请教！

### ISSUE THREAD

**Issue by shledon** [WangXuan95/FpOC#4]
请问作者电流采样为什么选取三电阻，二电阻采样不是更方便吗，在已知偏置电压和放大倍数的情况下，ia,ib不就和ADC一一对应了吗

**Comment by WangXuan95** [comment]
在知道偏置电压时当然是可以二电阻采样，只不过你不一定知道偏置电压，在我画的这个电机驱动的电路里，偏置电压是一颗 AMS1117-1.2 产生的，实际上每颗情况可能不一样，电压会有正负0.0几V的差距，而且还会有温飘时漂，用三电阻采样就能消除这些因素带来的误差。另外我用的MP6050芯片刚好自带三路电阻采样放大，ADC芯片也是8路的，因此三电阻采样和二电阻采样成本是一样的。肯定也有些驱动方案里偏置比较精确，且二电阻时可以省成本，这种情况下就要用二电阻了

**Comment by shledon** [comment]
感谢回答，基于你的方案确实三电阻是更好的选择。
