### ISSUE TITLE
Pi控制器的kp和ki为什么在程序中固定

### ISSUE THREAD

**Issue by hello110300509** [WangXuan95/FpOC#8]
您好，我学习您的工程，受益匪浅，但是有个疑问：为什么kp，ki直接在程序中固定呢？谢谢！

**Comment by WangXuan95** [comment]
你好，其实确实应该做成可配置的接口，但我当时没做那么完整，可能后续会更新。你可以初步自己先改一下。

**Comment by WangXuan95** [comment]
我改了一下，现在它不是固定的了，运行时也可变了
